In [1]:
import numpy as np
import matplotlib.pyplot as plt
import joblib
class Perceptron():
    def __init__(self,eta:float=None,epoch:float=None):
        self.eta=eta
        self.epoch=epoch
        self.weight=np.random.rand(3)*1e-4
    def fit(self,X,y):
        self.X=X
        self.y=y
        x_with_bias=np.c_[self.X,np.ones((len(self.X),1))]
        print (f'X with biases is:\n {x_with_bias}')
    def trial(self,x:int=None,y:int=None):
        return x
    def var(self):
        self.m=40
        return self.m
    def pf(self):
        var=self.m
        return var
        

In [130]:
obj2=Perceptron()

In [131]:
obj2.var()

40

In [132]:
obj2.pf()

40

In [4]:
np.dot(1,2)

2

In [16]:
a=np.array([[2,3,4,5],[3,2,3,5]])

In [18]:
b=np.array([[2,3],[3,4],[5,6],[7,8]])

In [19]:
b

array([[2, 3],
       [3, 4],
       [5, 6],
       [7, 8]])

In [20]:
c=a@b

In [21]:
c

array([[68, 82],
       [62, 75]])

In [22]:
np.dot(a,b)

array([[68, 82],
       [62, 75]])

In [24]:
a = np.arange(3*4*5*6).reshape((3,4,5,6))
#b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))
#np.dot(a, b)[2,3,2,1,2,2]

In [36]:
np.arange(3*4*5*6).reshape(3,4,5,6)

array([[[[  0,   1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10,  11],
         [ 12,  13,  14,  15,  16,  17],
         [ 18,  19,  20,  21,  22,  23],
         [ 24,  25,  26,  27,  28,  29]],

        [[ 30,  31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40,  41],
         [ 42,  43,  44,  45,  46,  47],
         [ 48,  49,  50,  51,  52,  53],
         [ 54,  55,  56,  57,  58,  59]],

        [[ 60,  61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70,  71],
         [ 72,  73,  74,  75,  76,  77],
         [ 78,  79,  80,  81,  82,  83],
         [ 84,  85,  86,  87,  88,  89]],

        [[ 90,  91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100, 101],
         [102, 103, 104, 105, 106, 107],
         [108, 109, 110, 111, 112, 113],
         [114, 115, 116, 117, 118, 119]]],


       [[[120, 121, 122, 123, 124, 125],
         [126, 127, 128, 129, 130, 131],
         [132, 133, 134, 135, 136, 137],
         [138, 139, 140, 141, 142, 143],
      

In [49]:
np.arange(200).reshape(5,2,2,10)

array([[[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39]]],


       [[[ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59]],

        [[ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79]]],


       [[[ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114, 115, 116, 117, 118, 119]]],


       [[[120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
         [130, 131, 132, 133, 134, 135, 136, 137, 138, 139]],

        [[140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
         [150, 151, 152, 153, 154, 155, 156, 157, 158, 159]]],


