In [272]:
import numpy as np
import matplotlib.pyplot as plt
import joblib
class Perceptron():
    
    def __init__(self,eta:float=None,epoch:float=None):
        self.eta=eta # learning rate
        self.epoch=epoch # iterations
        self.weight=np.random.rand(3)*1e-4
        
    def _z_value(self,input,weight):
        return np.dot(input,weight)
    
    def step_activate(self,z_value):
        return np.where(z_value>0,1,0)
    
    def fit(self,X,y):
        self.X=X
        self.y=y
        x_with_bias=np.c_[self.X,-np.ones((len(self.X),1))]
        print (f'X with biases is:\n {x_with_bias}')
        for iter in range(self.epoch):
            z=self._z_value(x_with_bias,self.weight)
            y_hat=self.step_activate(z)
            self.error=self.y-y_hat
            self.weight=self.weight+self.eta*np.dot(x_with_bias.T,self.error)
    def predict(self,x):
        x_with_bias=np.c_[x,-np.ones(len(x))]
        y_hat=self._z_value(x_with_bias,self.weight)
        return self.step_activate(y_hat)
        
            
            
            
            
        

In [394]:
import numpy as np
class Perceptron1:
    def __init__(self,epoch:float=None,eta:float=None):#class initialization
        
        self.iter=epoch
        
        self.learning=eta
        
        self.weight=np.random.rand(3)*1e-4
        
    def _z_value(self,input,weight):#---------------------for z value determination
        
        return np.dot(input,weight)
    
    def _step_func(self,z_value):#------------step function for 0 or 1 class
        
        return np.where(z_value>=0,1,0)
    
    
    
    def fit(self,x,y): #-----------------to fit inside the model
        self.x=x
        self.y=y
        x_with_bias=np.c_[self.x,-np.ones((len(self.x),1))]
        print(f'x_with_biases:\n{x_with_bias}')
        
        for epoch in range(self.iter):
            print(f'this is for the epoch:{epoch+1}/{self.iter} \n')
            
            z=self._z_value(x_with_bias,self.weight)
            
            self.y_hat=self._step_func(z)
            print(f'predicted value is:\n {self.y_hat} \n')
            
            self.error=self.y-self.y_hat
            print(f'the error values are given by:\n{self.error} \n')
           
            
            self.weight=self.weight+self.learning*np.dot(x_with_bias.T,self.error)
            print(f'the updated weight values is:  \n{self.weight} \n')
            
            print('*'*50)
            
            
    def predict(self,x):
        x_with_bias=np.c_[x,-np.ones((len(x),1))]
        z=self._z_value(x_with_bias,self.weight)
        return self._step_func(z)
        
        

In [395]:
def data_extrac(df,target_col='y'):
        x=df.drop(target_col,axis=1)
        y=df[target_col]
        return x,y

In [396]:
dic={'x1':[0,0,1,1],'x2':[0,1,0,1],'y':[0,0,0,1]}
import pandas as pd
df=pd.DataFrame(dic)

In [397]:
x,y=data_extrac(df,target_col='y')

In [398]:
or_gate.predict(x)

array([0, 0, 0, 1])

In [406]:
epoch=7
eta=0.1
or_gate=Perceptron1(epoch=epoch,eta=eta)
or_gate.fit(x,y)

x_with_biases:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
this is for the epoch:1/7 

predicted value is:
 [0 1 1 1] 

the error values are given by:
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64 

the updated weight values is:  
[-0.09993256 -0.09991995  0.20005105] 

**************************************************
this is for the epoch:2/7 

predicted value is:
 [0 0 0 0] 

the error values are given by:
0    0
1    0
2    0
3    1
Name: y, dtype: int64 

the updated weight values is:  
[6.74390043e-05 8.00478404e-05 1.00051050e-01] 

**************************************************
this is for the epoch:3/7 

predicted value is:
 [0 0 0 0] 

the error values are given by:
0    0
1    0
2    0
3    1
Name: y, dtype: int64 

the updated weight values is:  
[1.00067439e-01 1.00080048e-01 5.10501893e-05] 

**************************************************
this is for the epoch:4/7 

predicted value is:
 [0 1 1 1] 

the error values are given by:
0    0
1   -1

In [407]:
or_gate.predict(x)

array([0, 0, 0, 1])